spring.application.name=recommendation-service
server.port=8080

# ???????? ?? (H2)
application.recommendations-db.url=jdbc:h2:file:./transaction

# ?????? ?? (H2 in-memory) ? ??? ???????????? ??????
app.dynamic-db.url=jdbc:h2:mem:dynamic_db;DB_CLOSE_DELAY=-1
app.dynamic-db.username=sa
app.dynamic-db.password=
app.dynamic-db.driverClassName=org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.liquibase.enabled=false

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Telegram bot
telegram.bot.token=8316928633:AAGzyGHFT2_CWz2rwvn0RL1yLd9FCDtPkBc
telegram.bot.username=First_my_Sky_bot

# Build info
spring.info.build.location=classpath:META-INF/build-info.properties

# ???????????
debug=true
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.liquibase=DEBUG